/**
 * Connection trend reports: record snapshots, generate PDF.
 */
const PDFDocument = require('pdfkit');
const db = require('../config/database');
const mikrotikService = require('./mikrotikService');

/**
 * Record a connection snapshot for a router. Called periodically by the server.
 */
async function recordSnapshot(router) {
  try {
    const stats = await mikrotikService.getConnectionStats(router);
    const count = stats.hotspotEnabled
      ? (stats.hotspotUsers || []).length
      : (stats.dhcpLeaseCount || 0);
    await db.query(
      `INSERT INTO router_connection_snapshots (router_id, recorded_at, hotspot_enabled, connection_count)
       VALUES (?, NOW(), ?, ?)`,
      [router.id, stats.hotspotEnabled ? 1 : 0, count]
    );
  } catch (err) {
    const msg = err?.message || err?.code || String(err) || 'Unknown';
    console.warn(`[ConnectionReport] Snapshot failed for router ${router.id}:`, msg);
  }
}

/**
 * Fetch connection history for a router in a date range.
 */
async function getConnectionHistory(routerId, fromDate, toDate) {
  const [rows] = await db.query(
    `SELECT recorded_at, hotspot_enabled, connection_count
     FROM router_connection_snapshots
     WHERE router_id = ? AND DATE(recorded_at) BETWEEN ? AND ?
     ORDER BY recorded_at ASC`,
    [routerId, fromDate, toDate]
  );
  return rows;
}

/**
 * Generate a PDF report for router connection trends.
 */
function generateReportPdf(routerName, location, fromDate, toDate, history, options = {}) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const hotspotOnLabel = 'Hotspot ON: Users (voucher)';
    const hotspotOffLabel = 'Hotspot OFF: Devices (DHCP)';

    // Header
    doc.fontSize(18).font('Helvetica-Bold').text('Connection Trend Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(12).font('Helvetica').text(routerName, { align: 'center' });
    if (location) doc.text(location, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#666666').text(`Period: ${fromDate} to ${toDate}`, { align: 'center' });
    doc.moveDown(0.8).fillColor('#000000');

    // Legend
    doc.fontSize(9).font('Helvetica');
    doc.text('• Hotspot ON = voucher users currently logged in', 50, doc.y);
    doc.text('• Hotspot OFF = DHCP devices on network (target market size)', 50, doc.y + 12);
    doc.moveDown(1);

    // Summary stats
    if (history.length > 0) {
      const counts = history.map((h) => h.connection_count);
      const max = Math.max(...counts);
      const min = Math.min(...counts);
      const avg = Math.round(counts.reduce((a, b) => a + b, 0) / counts.length);
      const hotspotOnRows = history.filter((h) => h.hotspot_enabled);
      const hotspotOffRows = history.filter((h) => !h.hotspot_enabled);

      doc.fontSize(11).font('Helvetica-Bold').text('Summary', 50, doc.y);
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10);
      doc.text(`Data points: ${history.length}`);
      if (hotspotOnRows.length > 0) doc.text(`Peak (hotspot ON): ${Math.max(...hotspotOnRows.map((h) => h.connection_count))} users`);
      if (hotspotOffRows.length > 0) doc.text(`Peak (hotspot OFF): ${Math.max(...hotspotOffRows.map((h) => h.connection_count))} devices`);
      doc.text(`Overall max: ${max}`);
      doc.text(`Overall min: ${min}`);
      doc.text(`Average: ${avg}`);
      doc.moveDown(1);
    }

    // Data table
    doc.fontSize(11).font('Helvetica-Bold').text('Recorded Data', 50, doc.y);
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(9);

    const col1 = 50;
    const col2 = 200;
    const col3 = 480;

    doc.text('Date & Time', col1, doc.y);
    doc.text('Hotspot State', col2, doc.y);
    doc.text('Count', col3, doc.y);
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.2);

    for (const row of history) {
      const d = new Date(row.recorded_at);
      const dateStr = d.toLocaleString('en-GB', { dateStyle: 'short', timeStyle: 'short' });
      const stateStr = row.hotspot_enabled ? hotspotOnLabel : hotspotOffLabel;
      doc.text(dateStr, col1, doc.y);
      doc.text(stateStr, col2, doc.y, { width: 270 });
      doc.text(String(row.connection_count), col3, doc.y);
      doc.moveDown(0.35);

      if (doc.y > 700) {
        doc.addPage();
        doc.y = 50;
      }
    }

    if (history.length === 0) {
      doc.text('No recorded data for this period.', col1, doc.y);
      doc.text('Snapshots are recorded every 15 minutes when the router is online.', col1, doc.y + 12);
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999999');
    doc.text(`Generated by RouterHub on ${new Date().toISOString()}`, 50, doc.y);
    doc.end();
  });
}

module.exports = {
  recordSnapshot,
  getConnectionHistory,
  generateReportPdf,
};
